### ISSUE TITLE
AuditorPraise - Vault.settle() won't be able to rebalance the collateral and position of the vault

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-perennial-judging#6]
AuditorPraise

medium

# Vault.settle() won't be able to rebalance the collateral and position of the vault

## Summary
Vault.settle() is supposed to  rebalance the collateral and position of the vault without a deposit or withdraw but this won't happen because `bool rebalance` is set as false when calling Vault._manage().

## Vulnerability Detail
Vault._manage() has 3 params: `context`, `withdrawAmount`, and `bool rebalance`. 

The value of `bool rebalance` determines whether to rebalance the vault's position or not. 

Now the issue is when Vault.settle() calls _manage(), it sets `bool rebalance` as false, see [here](https://github.com/sherlock-audit/2023-10-perennial/blob/main/perennial-v2/packages/perennial-vault/contracts/Vault.sol#L224). 

Now this if statement [here](https://github.com/sherlock-audit/2023-10-perennial/blob/main/perennial-v2/packages/perennial-vault/contracts/Vault.sol#L391) will return the execution without rebalancing the collateral and position of the vault.

## Impact
Vault.settle() won't be able to rebalance the collateral and positions of the vault
## Code Snippet
https://github.com/sherlock-audit/2023-10-perennial/blob/main/perennial-v2/packages/perennial-vault/contracts/Vault.sol#L224

https://github.com/sherlock-audit/2023-10-perennial/blob/main/perennial-v2/packages/perennial-vault/contracts/Vault.sol#L391
## Tool used

Manual Review

## Recommendation
`bool rebalance` should be set to `true` and not `false` within Vault.settle(), since its supposed to  rebalance the collateral and position of the vault

**Comment by AuditorPraise** [comment]
Escalate.

According to sponsor Vault.settle() is supposed to rebalance the collateral and positions of the vault.

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> According to sponsor Vault.settle() is supposed to rebalance the collateral and positions of the vault. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by AuditorPraise** [comment]
escalate 
IMO, since _settle() will process and update an acct's position in the settle(), The vault's positions and collateral in the market should be adjusted(rebalanced)
